volumes:
  node_modules:
  public:

services:
  justice-ai:
    build:
      context: .
      target: base-app
    container_name: ai-web
    env_file:
      - .env
    volumes:
      - public:/usr/share/nginx/html
    ports:
      - "80:8080"
    depends_on:
      node:
        condition: service_started
        restart: true

  node:
    container_name: ai-node
    build:
      context: .
      target: assets-dev
    working_dir: /home/node
    tty: true
    stop_grace_period: 0s
    command: make node-assets
    volumes:
      - node_modules:/home/node/node_modules
      - public:/home/node/dist
      - ./package.json:/home/node/package.json
      - ./src:/home/node/src
      - ./utils:/home/node/utils
      - ./scripts/.eleventy.js:/home/node/.eleventy.js
      - ./scripts/tailwind.config.js:/home/node/tailwind.config.js
      - ./Makefile:/home/node/Makefile
      - ./.markdownlint.json:/home/node/.markdownlint.json